project:
  name: taskcat-demo-project
  regions:
  - us-east-1
  - us-west-1
  - eu-west-1
tests:
  vpc-defaults:
    template: ./templates/create_ec2.yml
    regions:
    - us-east-1
    - us-west-1
    - eu-west-1    
    parameters:
      NameOfService: "TaskCat demo"
